# SPDX-License-Identifier: MIT-0
---
# tasks file for ipv64_blocklist

- name: Get blocklist
  ansible.builtin.set_fact:
    ip64_blocklist: "{{ lookup('ansible.builtin.url', 'https://ipv64.net/blocklists/ipv64_blocklist_v4_all.txt', split_lines=False) | split('\n') }}"
- name: Template blocklist
  ansible.builtin.copy:
    dest: /etc/nftables/00-ip64_blocklist.nft
    mode: "0755"
    content: |
      #!/usr/sbin/nft -f

      table inet spam_blocklist
      delete table inet spam_blocklist
      table inet spam_blocklist {
        set ip64-v4-blocklist {
          type ipv4_addr
          elements = {
          {% for ip_range in ip64_blocklist %}
          {%- if ip_range %}
          {%- if loop.index == (ip64_blocklist|length)-1 %}
          {{ ip_range }}
          {% else %}
          {{ ip_range }},
          {% endif %}
          {%- endif %}
          {% endfor %}
          }
        }

        chain PREROUTING {
          type filter hook prerouting priority filter; policy accept;
          tcp dport { 22, 80, 443 } ip saddr @ip64-v4-blocklist counter reject with icmp type host-unreachable
        }
      }
