---

- name: Create directory
  ansible.builtin.file:
    path: tmp/server
    state: directory
    mode: "0755"

- name: Render interface template
  ansible.builtin.template:
    src: wg.j2
    dest: "/etc/wireguard/{{ interface_name }}.conf"
    # dest: "tmp/server/{{interface_name}}.conf"
    force: true
    mode: '700'
- name: Create postup script
  ansible.builtin.copy:
    dest: /etc/wireguard/postup.sh
    mode: '700'
    content: "{{ postup_script | default('') }}"
- name: Create postdown script
  ansible.builtin.copy:
    dest: /etc/wireguard/postdown.sh
    mode: '700'
    content: "{{ postdown_script | default('') }}"

- name: Bring down interface
  ansible.builtin.command: wg-quick down {{ interface_name }}
  changed_when: true
  failed_when: false

- name: Bring up interface
  ansible.builtin.command: wg-quick up {{ interface_name }}
  changed_when: true
