---
# vars file for zabbix-agent
archtiecture_mapping:
  aarch64: arm64
  x86_64: amd64

zabbix_agent: zabbix-agent
zabbix_agent_service: zabbix-agent
zabbix_agent_conf: zabbix_agentd.conf
zabbix_agent2_conf: zabbix_agent2.conf
