---
# tasks file for zabbix-agent
# https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_AGENT_ROLE.md
- name: Install zabbix agent
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_agent
  vars:
    zabbix_agent_version: "6.4"
    zabbix_agent2: true
    zabbix_agent2_server: "{{ zabbix_server | default('0.0.0.0/0') }}"
    zabbix_agent2_tlsaccept: "{{ tls_accept | default('psk') }}"
    zabbix_agent2_tlspskfile: "/etc/zabbix/zabbix.psk"
    zabbix_agent2_tlspskidentity: "{{ tls_identity }}"
    zabbix_agent2_tlspsk_secret: "{{ tls_psk }}"

    # zabbix_agent_listenip: "0.0.0.0"
    # zabbix_agent_hostname: "{{ hostname }}"

- name: Configure host on Server
  community.zabbix.zabbix_host:
    host_name: "{{ ansible_hostname }}"
    server_url: "{{ zabbix_url }}"
    validate_certs: "{{ validate_certs | default(true) }}"
    http_login_user: "{{ api_user | default() }}"
    http_login_password: "{{ api_password }}"
    interfaces:
      - type: "agent"
        useip: "{{ use_ip }}"
        ip: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"
        dns: "{{ hostname }}"
        main: "1"
    tls_connect: "{{ tls_accept | default(2) }}" # 1 (no encryption), 2 (PSK), 4 (certificate)
    tls_psk_identity: "{{ tls_identity }}"
    tls_psk: "{{ tls_psk }}"
    host_groups: "{{ host_groups }}"
    link_templates: "{{ templates }}"
  when: create_hosts
  delegate_to: localhost
