- name: Deploy userparameter
  ansible.builtin.include_role:
    name: community.zabbix.zabbix_agent
  vars:
    zabbix_agent_userparameters:
      - name: wireguard_iptables
        scripts_dir: wireguard
